### ISSUE TITLE
Neither Grommid nor Toad show AERC score

### ISSUE THREAD

**Issue by ironchestgames** [CorayThan/decks-of-keyforge-tickets#15]
**Describe the bug**
Neither Grommid nor Toad show their AERC score.

Guessing because the AERC is 0, it gets treated as null or something.

**To Reproduce**
1. Go to https://decksofkeyforge.com/cards/grommid
2. See no AERC

**Expected behavior**
Should see AERC score.

**Screenshots**
Example of other creature:
![Screenshot 2021-02-24 at 20 57 01](https://user-images.githubusercontent.com/24595262/109058409-44de3880-76e3-11eb-9e56-09abd8730ed6.png)

Grommid
![Screenshot 2021-02-24 at 20 56 48](https://user-images.githubusercontent.com/24595262/109058430-4871bf80-76e3-11eb-80d2-d56c01e24b0a.png)

**Desktop (please complete the following information):**
 - OS: MacOS Mojave 10.14.5 (18F132)
 - Browser: Chrome 
 - Version 88.0.4324.146 (Official Build) (x86_64)

**Smartphone (please complete the following information):**

**Additional context**
-

**Comment by CorayThan** [comment]
They're so bad / such low score this doesn't show for them.
