### ISSUE TITLE
Prince Derric, Unifier has 0% synergie with Replay Creature (like exhume)

### ISSUE THREAD

**Issue by Osarek** [CorayThan/decks-of-keyforge-tickets#17]
for example in this deck with 3exhume, and 1 prince derric
https://decksofkeyforge.com/decks/eea3ba1d-9b87-46d4-9853-1950aef7cac8

**Comment by Osarek** [comment]
wrong label sorry

**Comment by Osarek** [comment]
also Exhume does not count Prince derric for a "good creature"
![image](https://user-images.githubusercontent.com/57572496/110975626-46a13080-8360-11eb-8cf2-665f58434185.png)

**Comment by CorayThan** [comment]
Added a new synergy for plays creatures from out of house that I think works better for this.
