### ISSUE TITLE
Imaginary Deck

### ISSUE THREAD

**Issue by avcwisesa** [CorayThan/decks-of-keyforge-tickets#18]
**Describe what you would like changed or added.**

Feature to create imaginary deck & calculate SAS for it. User will be able to choose the set, houses & cards (which are available to the set selected).

**Describe how this change would improve your experience as a KeyForge player.**

We're holding a community auction where we open a box & bid just by reading the card list. Because the deck is not registered yet we cannot see the deck as a "deck" and needs to see each card back and forth. Having this feature will help to see the unregistered deck as a deck and not as individual cards.

**Comment by CorayThan** [comment]
This already exists! The link is on the deck importer menu.

https://decksofkeyforge.com/theoretical-decks/create
