### ISSUE TITLE
"housesAndCards" on API/v1/my-decks has dissapeared

### ISSUE THREAD

**Issue by CarlosJLopez** [CorayThan/decks-of-keyforge-tickets#19]
**Describe the bug**
For any reason the ""housesAndCards" info has dissapeared on API/v1/my-decks results 

**To Reproduce**
Call to https://decksofkeyforge.com/public-api/v1/my-decks with own APIKey.

**Expected behavior**
Results may contain "housesAndCards" filled on each deck.

**Screenshots**
![image](https://user-images.githubusercontent.com/7148584/114301533-9856eb00-9ac5-11eb-887f-3149d3353f1c.png)

**Comment by CorayThan** [comment]
@CarlosJLopez I had to remove that part of the API, unfortunately. With large collections it was causing the service to fail.

**Comment by CarlosJLopez** [comment]
Is there an option to obtain the three houses of the deck?

**Comment by SeiferTim** [comment]
> Is there an option to obtain the three houses of the deck?

This is also something that is crucial for me.
