### ISSUE TITLE
Bonus icons for Dark Tidings decks are incorrect

### ISSUE THREAD

**Issue by cmorenoserrano** [CorayThan/decks-of-keyforge-tickets#21]
********
This is not for reporting problems with the SAS or AERC rating of cards / decks! Use the Card change report template for that.
********

**Describe the bug**
I have started importing my new DT decks into DoK and I have noticed that the bonus icons are generally wrong (missing entirely or incorrectly reported).

**To Reproduce**
Check for example these decks:

https://decksofkeyforge.com/decks/c7b29254-9f49-4679-9e4c-e7ac006a8651
It is showing one bonus icon of each type, however it should have 7 capture bonus icons instead of just one.

Another example below, where no bonus icons are reported, however you can see the enhanced cards in blue:
https://decksofkeyforge.com/decks/1baed224-eaa0-403f-a62e-e96c4b2049ed

**Expected behavior**
Bonus icons are correctly displayed.

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by CorayThan** [comment]
This will be fixed when DT SAS is released.
