### ISSUE TITLE
Link Both twin deck (by link or icon)

### ISSUE THREAD

**Issue by Osarek** [CorayThan/decks-of-keyforge-tickets#23]
I think it would be nice if there were a link next to the title of an Evil Twin deck that redirect to the "Normal Twin" deck if it has already been scanned.
Maybe a link from "Normal Twin" to "Evil Twin" is not necesarry

This could save time for the player wich are looking to buy the other twin.

And also to just know if you have a chance (even if its tiny) to play aigainst its twin

**Comment by CorayThan** [comment]
Adding this today! Decks will fill out their twin links over the next few days as the system processes existing decks.
