### ISSUE TITLE
Enhanced card does not show up blue

### ISSUE THREAD

**Issue by avandever** [CorayThan/decks-of-keyforge-tickets#24]
********
This is not for reporting problems with the SAS or AERC rating of cards / decks! Use the Card change report template for that.
********

**Describe the bug**
Rustmiser on this deck is enhanced, but DOK does not show it.
https://decksofkeyforge.com/decks/6d3d0cfb-a483-4b4f-94a6-61a10aa049a4

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version 89.0.4389.128 (Official Build) (64-bit)

**Comment by CorayThan** [comment]
This should be fixed in a few days after I deploy this next fix today.
