### ISSUE TITLE
Add AERC constraints for cards when searching for decks

### ISSUE THREAD

**Issue by ghoxie** [CorayThan/decks-of-keyforge-tickets#3]
I often search for decks with specific cards and usually I would like that card I am searching for to be at least "good" in that deck.

For instance, if I wanted a deck with Imperial Forge, it would be nice if I could specify that I only want to see decks where Imperial Forge is at >75% of its AERC range.

**Comment by CorayThan** [comment]
That's a cool idea! Unfortunately that would be technically infeasible, so I won't be able to do that.
