### ISSUE TITLE
Bull-wark, Eureka!, and Taniwha (ET) have synergies but no range

### ISSUE THREAD

**Issue by r0gershrubber** [CorayThan/decks-of-keyforge-tickets#31]
******************************************
Read and follow the SAS Change request guidelines: 
https://github.com/CorayThan/decks-of-keyforge-tickets#sas-change-request-guidelines 
******************************************

### Additional Card Names

Bull-wark, Eureka!, Taniwha (ET)

### Rational

As discussed on the discord, Bull-wark synergizes with Causes Fighting, but it has no synergy range, so the synergy doesn't do anything. Eureka has anti-synergy with other alpha cards in house, but again no synergy range. And Taniwha (ET) has synergy with good creatures, but no synergy range. My suggested synergy ranges are based on Ancient Bear for Bull-wark and World Tree for Taniwha. 

### AERC Changes

Bull-wark - set Creature Control: 0 to 0.5
Eureka! - set Efficiency to 0.25 to 0.5
Taniwha (ET) - set Recursion to 0 to 2

### Synergy or Trait Changes

Taniwhat (ET) - add synergies as World Tree

**Comment by Novalaina** [comment]
Fixed!
