### ISSUE TITLE
House mapping for Anomalies doubled up in CSV file (and presumably DB)

### ISSUE THREAD

**Issue by mlvanbie** [CorayThan/decks-of-keyforge-tickets#6]
**Describe the bug**

For some decks with N anomalies, there are 2N house mappings for the card in the all-decks CSV files.  This has been going on for years.

**To Reproduce**

1. grep ^005a9fba-1789-4be9-b621-b2446e981246 dok-decks-2021-01-19.csv
`005a9fba-1789-4be9-b621-b2446e981246,Demente Evans,452,Shadows|Untamed|Saurian,66,12,1,55,13.200000000000001,18.72125,0,12.149999999999999,0,0,0,3.75,2.03125,94,8,10,2,17,1,2,2,1,~Auto-Legionary1~Breaker Hill1~Brend the Fanatic1~Brutodon Auxiliary1~City Gates1~Deepwood Druid1~Eldest Bear1~Fangtooth Cavern1~Flaxia1~Fogbank1~Ghostform1~Hit and Run1~Hugger-Mugger1~Inky Gloom1~Instrument of Silence1~Key Charge1~Keyforgery1~Legatus Raptor1~Musthic Murmook1~Phalanx Strike1~Praefectus Ludo12~Skeleton Key1~Song of the Wild1~Spike Trap1~Stomp1~Symon12~The Golden Spiral1~The Shadow Council1~Thero Centurion1~Tricerian Legionary1~Unnatural Selection1~Unsuspecting Prey12~Yantzee Gang1~GhostformSaurian~GhostformSaurian~`

**Expected behavior**

`005a9fba-1789-4be9-b621-b2446e981246,Demente Evans,452,Shadows|Untamed|Saurian,66,12,1,55,13.200000000000001,18.72125,0,12.149999999999999,0,0,0,3.75,2.03125,94,8,10,2,17,1,2,2,1,~Auto-Legionary1~Breaker Hill1~Brend the Fanatic1~Brutodon Auxiliary1~City Gates1~Deepwood Druid1~Eldest Bear1~Fangtooth Cavern1~Flaxia1~Fogbank1~Ghostform1~Hit and Run1~Hugger-Mugger1~Inky Gloom1~Instrument of Silence1~Key Charge1~Keyforgery1~Legatus Raptor1~Musthic Murmook1~Phalanx Strike1~Praefectus Ludo12~Skeleton Key1~Song of the Wild1~Spike Trap1~Stomp1~Symon12~The Golden Spiral1~The Shadow Council1~Thero Centurion1~Tricerian Legionary1~Unnatural Selection1~Unsuspecting Prey12~Yantzee Gang1~!GhostformSaurian~
`
**Additional context**

This doesn't happen with all decks.  It happens with all anomalies.  It doesn't happen for Untamed Ghostform, which is what DoK considers to be the correct house.  This is particularly annoying if there are multiple copies of an anomaly in a deck.

**Comment by mlvanbie** [comment]
DoK's idea of correct house doesn't appear to be relevant.  There are decks (971d706b-0960-45f8-a81a-f224d6395544) that have legitimate doubles.  I found a deck that has two copies of Ghostform in Brobnar but only one house assignment (fe274c61-71d3-46bf-99d0-ad3248a975a6) -- got to protect those Narps!

**Comment by CorayThan** [comment]
Fixed this moving forward. Don't plan to fix the existing ones with duplicates as this should have no user problem on DoK.
